// Register
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';
export const REGISTER_LOADING = 'REGISTER_LOADING';

//Login
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_LOADING = 'LOGIN_LOADING';

//Contacts
export const CONTACT_LOADING = 'CONTACT_LOADING';
export const CONTACT_LOAD_SUCCESS = 'CONTACT_LOAD_SUCCESS';
export const CONTACT_LOAD_ERROR = 'CONTACT_LOAD_ERROR';

//Create contacts
export const CREATE_CONTACT_LOADING = 'CREATE_CONTACT_LOADING';
export const CREATE_CONTACT_SUCCESS = 'CREATE_CONTACT_SUCCESS';
export const CREATE_CONTACT_ERROR = 'CREATE_CONTACT_ERROR';


//UTILS
export const CONNECTION_ERROR = 'CONNECTION_ERROR';
export const USER_LOGOUT = 'USER_LOGOUT';
export const CLEAR_CREATE_CONTACT = 'CLEAR_CREATE_CONTACT';
export const FIREBASE_IMAGE_PATH = 'images';